apps/LR/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index , name ="index"),
    url(r'^register$', views.register, name ="register"),
    url(r'^success$', views.success, name ="success"),
    url(r'^login$', views.login, name ="login"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^main$', views.main, name="main"),
]

traveler/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include("apps.LR.urls", namespace="home")),
    url(r'^travels/', include("apps.travel.urls", namespace="travel"))
]

apps/LR/models.py
from django.db import models
from datetime import date
import re,bcrypt
# Create your models here.

class UserManager(models.Manager):
    def ValidForm(self, userData):
        errors = []
        if not userData['name'].isalpha():
            errors.append('Your name should be characters')
        if len(userData['name']) < 3:
            errors.append('Name must be at least 3 characters')
        if len(userData['username']) < 3:
            errors.append('Username must be at least 3 characters!')
        check_username = self.filter(username = userData['username'])
        if check_username:
            errors.append('Sorry .. Your Username is already exists!')
        if not len(userData['password']):
            errors.append('Please enter the Password')
        if len(userData['password']) < 8:
            errors.append('Password must be at least 8 long')
        if not userData['password'] == userData['confirm']:
            errors.append('Passwords must match!')


        modelsResponse = {}

        if errors:
            modelsResponse['isRegistered'] = False
            modelsResponse['errors'] = errors
        else:
            hashed_password = bcrypt.hashpw(userData['password'].encode(), bcrypt.gensalt())
            user = self.create(name = userData['name'],username = userData['username'], password = hashed_password)
            modelsResponse['isRegistered'] = True
            modelsResponse['user'] = user

        return modelsResponse

    def login_user(self, userData):
        user = self.filter(username = userData['username'])
        errors = []
        modelsResponse = {}
        if not user:
            errors.append('Invalid username')
        else:
            if bcrypt.checkpw(userData['password'].encode(), user[0].password.encode()):
                modelsResponse['isLoggedIn'] = True
                modelsResponse['user'] = user[0]

            else:
                errors.append('Username or Password is not correct')

        if errors:
            modelsResponse['isLoggedIn'] = False
            modelsResponse['errors'] = errors

        return modelsResponse


class User(models.Model):
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/LR/views.py
from django.shortcuts import render,redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):
    return redirect("home:main")

def main(request):
    return render(request, "LR/index.html")

def register(request):
    viewsResponse = User.objects.ValidForm(request.POST)
    if viewsResponse['isRegistered']:
        request.session['id'] = viewsResponse['user'].id
        request.session['name'] = viewsResponse['user'].name
        return redirect('travel:home')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('home:index')


def success(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in')
        return redirect('home:index')

def login(request):
    viewsResponse = User.objects.login_user(request.POST)
    if viewsResponse['isLoggedIn']:
        request.session['id'] = viewsResponse['user'].id
        request.session['name'] = viewsResponse['user'].name
        return redirect('travel:home')
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
        return redirect('home:index')

def logout(request):
    request.session.clear()
    return redirect('home:index')

apps/LR/templates/LR/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="Regi">
      {% if messages %}
        {% for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
      {% endif %}
      <h1>Registration</h1>
      <form class="" action="{% url 'home:register' %}" method="post">
        {% csrf_token %}
        <label for="name">Name : </label>
        <input type="text" name="name">
        <label for="username">Username : </label>
        <input type="text" name="username">
        <label for="password">Password : </label>
        <input type="password" name="password">
        <label for="confirm">Confirm pw : </label>
        <input type="password" name="confirm">
        <button type="submit" name="submit">Register</button>
      </form>
    </div>
    <div class="">
      <h1>Login !</h1>
      <form action="{% url 'home:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username : </label>
        <input type="text" name="username" value="">
        <label for="password">Password: </label>
        <input type="password" name="password" value="">
        <button type="submit" name="submit">Log In</button>
      </form>
    </div>

  </body>
</html>

apps/LR/templates/LR/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome, {{ request.session.fname}}</h1>
    <form class="" action="{% url 'home:logout' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Logout">

    </form>
  </body>
</html>