apps/travel/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name="home"),
    url(r'^logtout$', views.logout, name="logout"),
    url(r'^add$', views.add, name="add"),
    url(r'^info/(?P<id>\w+)/$', views.info, name="info"),
    url(r'^create$', views.create, name="create"),
    url(r'^join/(?P<id>\w+)/$', views.join, name="join"),
]

traveler/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include("apps.LR.urls", namespace="home")),
    url(r'^travels/', include("apps.travel.urls", namespace="travel"))
]

apps/travel/models.py
from __future__ import unicode_literals
from ..LR.models import User
from django.db import models
from datetime import datetime,date

class TravelManager(models.Manager):
    def add_plan(self, userData, user_id):

        errors = []
        if not len(userData['destination']):
            errors.append('Destination is required')

        if not len(userData['start_date']):
            errors.append('You did not select start date!')

        if not len(userData['end_date']):
            errors.append('You did not select end date!')

        if not len(userData['description']):
            errors.append('Tell me about the Travel!')

        if userData['start_date'] and userData['end_date']:
            today = datetime.now().date()
            print today
            start_date_select = datetime.strptime(userData['start_date'],'%Y-%m-%d').date()
            end_date_select = datetime.strptime(userData['end_date'],'%Y-%m-%d').date()
            if start_date_select < today:
                errors.append('Your startdate must to selected future date!')
            if start_date_select > end_date_select:
                errors.append('Your end date cannot before start date!')
            print start_date_select
            print end_date_select
        modelsResponse = {}

        if errors:
            modelsResponse['isRegistered'] = False
            modelsResponse['errors'] = errors

        else:
            LoginUser = User.objects.get(id=user_id)
            travel = self.create(destination = userData['destination'],description = userData['description'], creator = LoginUser, start_date = userData['start_date'], end_date = userData['end_date'])
            travel.travel_join.add(LoginUser)
            travel.save()
            modelsResponse['isRegistered'] = True
            modelsResponse['travel'] = travel

        return modelsResponse

    def join_travel(self, travel, user_id):
        LoginUser= User.objects.get(id=user_id)
        Travel_join = travel
        Travel_join.travel_join.add(LoginUser)
        Travel_join.save()

class Travel(models.Model):
    destination = models.CharField(max_length = 200)
    description = models.TextField()
    creator = models.ForeignKey(User, related_name="travel_owner")
    travel_join = models.ManyToManyField(User, related_name="travel_user")
    start_date = models.DateField(auto_now = False, auto_now_add = False)
    end_date = models.DateField(auto_now = False, auto_now_add = False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = TravelManager()

apps/travel/views.py
from django.shortcuts import render,redirect
from ..LR.models import User
from .models import Travel
from django.contrib import messages
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in')
        return redirect('home:index')
    context = {
        "travels" : Travel.objects.filter(travel_join__id=request.session['id']).order_by('start_date'),
        "othertravels" : Travel.objects.exclude(travel_join__id=request.session['id']).exclude(creator=request.session['id']).order_by('start_date'),
    }
    return render(request,"travel/main.html",context)

def logout(request):
    request.session.clear()
    return redirect('home:index')

def add(request):
    if 'id' not in request.session:
        messages.error(request, 'Must be logged in')
        return redirect('home:index')
    else:
        return render(request,"travel/add.html")

def create(request):
    viewsResponse = Travel.objects.add_plan(request.POST, request.session['id'])
    if viewsResponse['isRegistered']:
        return redirect(reverse('travel:home'))
    else:
        for error in viewsResponse['errors']:
            messages.error(request, error)
            return redirect('travel:add')

def info(request, id):
    context = {
        "travel_info" : Travel.objects.filter(id=id),
    }
    return render(request, "travel/info.html", context)

def join(request, id):
    travel_id = Travel.objects.get(id=id)
    Travel.objects.join_travel(travel_id, request.session["id"])
    return redirect('travel:home')

apps/travel/templates/travel/add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      p{
        color:red;
      }
    </style>
  </head>
  <body>
    <a href="{% url 'travel:home' %}">Home</a>
    <a href="{% url 'travel:logout'%}">Logout</a>
    <form class="" action="{% url 'travel:create' %}" method="post">
      {% csrf_token %}
      <label for="destination">Destination :</label>
      <input type="text" name="destination">
      <label for="description">Description :</label>
      <input type="text" name="description">
      <label for="start_date">Travel Date From: </label>
      <input type="date" name="start_date">
      <label for="end_date">Travel Date To: </label>
      <input type="date" name="end_date">
      <button type="submit" name="submit">Add</button>
    </form>
      {% if messages %}
        {% for message in messages %}
          <p>{{message}}</p>
        {% endfor %}
      {% endif %}
  </body>
</html>

apps/travel/templates/travel/info.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      <h2>Travel Info Page</h2>
      <a href="{% url 'travel:home' %}">Home</a>
      <a href="{% url 'travel:logout'%}">Logout</a>
      {% for travel in travel_info%}
      <h2>{{travel.destination}}</h2>
        <p>Planned By : {{travel.creator.name}}</p>
        <p>Description : {{travel.description}}</p>
        <p>Travel Date From : {{travel.start_date}}</p>
        <p>Travel Date To : {{travel.end_date}}</p>
    </div>
    <div class="">
      <h2>Other users' joining the trip:</h2>
        <ul>
          {% for jointraveler in travel.travel_join.all %}
            <li>{{jointraveler.name}}</li>
          {% endfor %}
        </ul>
      {% endfor %}
    </div>
  </body>
</html>

apps/travel/templates/travel/main.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <style media="screen">
      table{
        border: 1px solid black;
      }
    </style>
  </head>
  <body>
    <h2>Hello {{request.session.name}}</h2>
    <a href="{% url 'travel:logout'%}"><button type="submit" name="logout">Logout</button></a>

    <div class="">
      <h3>Your Trip Schedules</h3>
      <table>
        <tr>
          <td>Destination</td>
          <td>Travel Start Date</td>
          <td>Travel End Date</td>
          <td>Plan</td>
        </tr>
        {% for travel in travels%}
        <tr>
          <td><a href="{% url 'travel:info' id=travel.id%}">{{travel.destination}}</a></td>
          <td>{{travel.start_date}}</td>
          <td>{{travel.end_date}}</td>
          <td>{{travel.description}}</td>
        </tr>
        {% endfor %}
      </table>
    </div>

    <div class="">
      <h3>Other User's Travel Plans</h3>
      <table>
        <tr>
          <td>Name</td>
          <td>Destination</td>
          <td>Travel Start Date</td>
          <td>Travel End Date</td>
          <td>Do You want to Join?</td>
        </tr>

        {% for travel_other in othertravels%}
        <tr>
          <td>{{travel_other.creator.name}}</td>
          <td><a href="{% url 'travel:info' id=travel_other.id%}">{{travel_other.destination}}</a></td>
          <td>{{travel_other.start_date}}</td>
          <td>{{travel_other.end_date}}</td>
          <td><a href="{% url 'travel:join' id=travel_other.id%}">Join</a></td>
        </tr>
        {% endfor %}
      </table>
    </div>

    <a href="{% url 'travel:add'%}">Add Travel Plan</a>
  </body>
</html>